import { describe, it, expect } from 'vitest';
import {
  renderPullRequestComment,
  buildCheckRun,
  buildAnnotations,
  COMMENT_MARKER,
  MAX_ANNOTATIONS,
} from '@/guardian/report';
import type { ReportContext } from '@/guardian/report';
import { assessPullRequestRisk } from '@/guardian/risk';
import type { Finding } from '@/scanner/types';
import type { Severity, Category } from '@/db/schema';
import type { PullRequestFile } from '@/github/client';

const ctx: ReportContext = {
  repositoryFullName: 'acme/api',
  pullRequestNumber: 42,
  headSha: 'abc1234def5678',
  detailsUrl: 'https://sentinel.test/guardian?repo=r1',
  failOnSeverity: 'high',
};

function file(filename: string, changes = 10): PullRequestFile {
  return { filename, status: 'modified', additions: changes, deletions: 0, changes };
}

function finding(overrides: Partial<Finding> = {}): Finding {
  return {
    fingerprint: `fp-${Math.random()}`,
    ruleId: 'security/sql-injection',
    scannerId: 'security',
    severity: 'high',
    category: 'security',
    title: 'SQL injection via string concatenation',
    description: 'User input is concatenated into a SQL query.',
    filePath: 'src/db/users.ts',
    lineStart: 42,
    lineEnd: 44,
    evidence: 'db.query("SELECT * FROM users WHERE id = " + req.params.id)',
    confidence: 0.95,
    whyItMatters: 'An attacker can read or destroy the entire database.',
    remediation: 'Use a parameterised query.',
    references: [],
    relatedTests: [],
    metadata: {},
    ...overrides,
  };
}

function riskFor(newFindings: Finding[], extra: Partial<Parameters<typeof assessPullRequestRisk>[0]> = {}) {
  return assessPullRequestRisk({
    files: [file('src/db/users.ts')],
    newFindings,
    resolvedFingerprints: [],
    failOnSeverity: 'high',
    ...extra,
  });
}

describe('renderPullRequestComment', () => {
  it('includes the marker so the guardian can find and edit its own comment', () => {
    const body = renderPullRequestComment(riskFor([]), ctx);
    expect(body).toContain(COMMENT_MARKER);
  });

  it('leads with the verdict and the headline numbers', () => {
    const body = renderPullRequestComment(riskFor([finding()]), ctx);
    expect(body).toContain('CodeSentinel');
    expect(body).toMatch(/\*\*Risk\*\* \| [\d.]+\/100/);
    expect(body).toMatch(/\*\*New findings\*\* \| 1/);
  });

  it('explains each finding with why-it-matters and remediation', () => {
    const body = renderPullRequestComment(riskFor([finding()]), ctx);
    expect(body).toContain('SQL injection via string concatenation');
    expect(body).toContain('An attacker can read or destroy the entire database.');
    expect(body).toContain('Use a parameterised query.');
    expect(body).toContain('src/db/users.ts:42');
  });

  it('shows the risk factor breakdown so the score is explainable', () => {
    const body = renderPullRequestComment(riskFor([finding()]), ctx);
    expect(body).toContain('Why this risk score');
    expect(body).toContain('New findings introduced');
  });

  it('states that no code was modified', () => {

    const body = renderPullRequestComment(riskFor([]), ctx);
    expect(body).toMatch(/No code was modified/i);
  });

  it('attributes findings to deterministic analyzers, not an LLM', () => {
    const body = renderPullRequestComment(riskFor([]), ctx);
    expect(body).toMatch(/not generated by an LLM/i);
  });

  it('warns loudly when policy blocks the merge', () => {
    const body = renderPullRequestComment(riskFor([finding({ severity: 'critical' })]), ctx);
    expect(body).toContain('CAUTION');
    expect(body).toMatch(/Changes requested/);
  });

  it('discloses when analysis was incomplete instead of implying a clean result', () => {
    const body = renderPullRequestComment(riskFor([]), {
      ...ctx,
      degraded: [{ id: 'dependencies', status: 'error', message: 'advisory API unreachable' }],
    });
    expect(body).toContain('Incomplete analysis');
    expect(body).toContain('advisory API unreachable');
  });

  it('caps the listed findings and links out for the rest', () => {
    const many = Array.from({ length: 40 }, (_, i) => finding({ filePath: `src/f${i}.ts` }));
    const body = renderPullRequestComment(riskFor(many), ctx);
    expect(body).toMatch(/…and \d+ more/);
    expect(body).toContain(ctx.detailsUrl);
  });

  it('stays within GitHub comment size limits even with hundreds of findings', () => {
    const many = Array.from({ length: 400 }, (_, i) =>
      finding({ filePath: `src/f${i}.ts`, description: 'x'.repeat(500) }),
    );
    const body = renderPullRequestComment(riskFor(many), ctx);
    expect(body.length).toBeLessThanOrEqual(65_536);
  });

  it('reports resolved findings as credit', () => {
    const risk = riskFor([], { resolvedFingerprints: ['a', 'b'] });
    const body = renderPullRequestComment(risk, ctx);
    expect(body).toMatch(/\*\*Resolved\*\* \| 2/);
  });
});

describe('renderPullRequestComment — secret redaction', () => {
  const secretFinding = finding({
    ruleId: 'secret/aws-access-key',
    category: 'secrets' as Category,
    severity: 'critical',
    title: 'Hardcoded AWS access key',
    evidence: 'AKIA****************ABCD',
  });

  it('never prints evidence for a secret finding, even masked', () => {
    const body = renderPullRequestComment(riskFor([secretFinding]), ctx);
    expect(body).not.toContain('AKIA****************ABCD');
    expect(body).not.toContain('AKIA');
  });

  it('still reports the secret finding itself', () => {
    const body = renderPullRequestComment(riskFor([secretFinding]), ctx);
    expect(body).toContain('Hardcoded AWS access key');
    expect(body).toContain('src/db/users.ts');
  });

  it('does print evidence for a non-secret finding', () => {
    const body = renderPullRequestComment(riskFor([finding()]), ctx);
    expect(body).toContain('SELECT * FROM users WHERE id');
  });
});

describe('buildCheckRun', () => {
  it('concludes success when there are no new findings', () => {
    const check = buildCheckRun(riskFor([]), ctx);
    expect(check.conclusion).toBe('success');
    expect(check.output?.title).toMatch(/No new findings/);
  });

  it('concludes failure when policy blocks the merge', () => {
    const check = buildCheckRun(riskFor([finding({ severity: 'critical' })]), ctx);
    expect(check.conclusion).toBe('failure');
  });

  it('concludes neutral for findings below the blocking threshold', () => {

    const check = buildCheckRun(riskFor([finding({ severity: 'low' })]), ctx);
    expect(check.conclusion).toBe('neutral');
  });

  it('concludes action_required when an analyzer errored', () => {

    const check = buildCheckRun(riskFor([]), {
      ...ctx,
      degraded: [{ id: 'security', status: 'error', message: 'parser crash' }],
    });
    expect(check.conclusion).toBe('action_required');
    expect(check.output?.summary).toContain('parser crash');
  });

  it('treats a skipped analyzer as non-fatal but still reports it', () => {
    const check = buildCheckRun(riskFor([]), {
      ...ctx,
      degraded: [{ id: 'semgrep', status: 'skipped', message: 'binary not installed' }],
    });
    expect(check.conclusion).toBe('success');
  });

  it('targets the head sha and links back to the dashboard', () => {
    const check = buildCheckRun(riskFor([]), ctx);
    expect(check.headSha).toBe(ctx.headSha);
    expect(check.detailsUrl).toBe(ctx.detailsUrl);
    expect(check.status).toBe('completed');
  });
});

describe('buildAnnotations', () => {
  it('maps a finding to its file and line range', () => {
    const [annotation] = buildAnnotations([finding()]);
    expect(annotation).toMatchObject({
      path: 'src/db/users.ts',
      start_line: 42,
      end_line: 44,
      annotation_level: 'failure',
    });
    expect(annotation?.message).toContain('Use a parameterised query.');
  });

  it('maps severities to GitHub annotation levels', () => {
    const levels = (['critical', 'high', 'medium', 'low', 'info'] as Severity[]).map(
      (severity) => buildAnnotations([finding({ severity })])[0]?.annotation_level,
    );
    expect(levels).toEqual(['failure', 'failure', 'warning', 'warning', 'notice']);
  });

  it('skips findings with no file or line to point at', () => {
    const repoWide = finding({ filePath: null, lineStart: null, lineEnd: null });
    expect(buildAnnotations([repoWide])).toEqual([]);
  });

  it('respects the 50-annotation API limit', () => {
    const many = Array.from({ length: 120 }, (_, i) => finding({ filePath: `src/f${i}.ts` }));
    expect(buildAnnotations(many)).toHaveLength(MAX_ANNOTATIONS);
  });

  it('prioritises the worst findings when truncating', () => {
    const many = [
      ...Array.from({ length: 60 }, (_, i) => finding({ severity: 'low', filePath: `src/low${i}.ts` })),
      finding({ severity: 'critical', filePath: 'src/critical.ts' }),
    ];
    const annotations = buildAnnotations(many);
    expect(annotations[0]?.path).toBe('src/critical.ts');
  });

  it('omits raw_details for secret findings', () => {
    const [annotation] = buildAnnotations([
      finding({ category: 'secrets' as Category, ruleId: 'secret/token', evidence: 'ghp_REALTOKEN' }),
    ]);
    expect(annotation?.raw_details).toBeUndefined();
    expect(JSON.stringify(annotation)).not.toContain('ghp_REALTOKEN');
  });

  it('never emits an end_line before the start_line', () => {
    const [annotation] = buildAnnotations([finding({ lineStart: 90, lineEnd: 10 })]);
    expect(annotation!.end_line).toBeGreaterThanOrEqual(annotation!.start_line);
  });
});
